### ISSUE TITLE
Own Message Text Color

### ISSUE THREAD

**Issue by xnaas** [MiniDigger/thelounge-theme-mininapse#42] opened 2019-02-01 21:15 UTC
Your own messages currently are colored grey instead of white or something more readable while on 3.0, non-vue.

How it looks:

![error](https://irc.xnaas.info/uploads/4ad79f723f9d4f2a/Capture.PNG)

How it should look:

![good](https://irc.minidigger.me/uploads/4e9d5015e8728592/Screenshot_20190201-213132.png)

**Comment by k1nghat** [comment] 2019-02-01 21:16
confirmed on 3.0.

**Comment by fnutt** [comment] 2019-02-04 08:07
This is valid for 3.0.0, but not in vue branch.

Can you please say what needs to be changed, as both Minidigger and I use vue branch?

**Comment by xnaas** [comment] 2019-02-04 13:19
If I knew what needed to be changed, I'd have submitted a PR. 😉 

Mini said to submit an issue so he wouldn't forget to investigate, so I did. 👍

**Comment by xnaas** [comment] 2019-02-07 18:37
For whatever it's worth setting this in the custom CSS field resolves the issue:
```
#chat .self .text {
	color: #c5c1c1;
}
```
It matches your own message color with every other message. When using inspect element on user messages, the color is reported as `rgb(197, 193, 193)` rather than normal hex notation.

**Comment by MiniDigger** [comment] 2019-02-28 08:10
uuuhm, sorry for ignoring you, I have missed all notifications for this repo :/
now that vue is in master, I guess this no longer is an issue?

**Comment by xnaas** [comment] 2019-04-08 16:14
idk, it's still fucked in v3.0.1 of thelounge, but I guess it'll sort itself out someday...

**Comment by fnutt** [comment] 2019-04-26 08:27
Cloning TheLounge git and using master branch it's not an issue with self text.

Mininapse theme is ment to be working with the newest possible TheLounge. We've added fixes for earlier versions before, but I guess it's better for each user to add support for earlier versions themself, or use an older version of Mininapse which is working with their specific version.

Closing this issue. Thanks for reporting it.

**Closed by fnutt** 2019-04-26 08:27 UTC

**Comment by xnaas** [comment] 2019-05-07 01:16
3.0.1 is the latest version and it still doesn't work, but here's hoping it sorts itself out with vue or whatever. :D

**Comment by fnutt** [comment] 2019-05-07 08:46
The issue is that neither @MiniDigger or myself use the stable versions. We both clone from git, so we're even more up to date with the changes to The Lounge. Supporting the latest stable version will result in a significant amount of maintainenance work for us.

As I wrote above, I think it's better if each and everyone fixes issues that arrise when using older or latest stable version. For those that may have this issue, please see https://github.com/MiniDigger/thelounge-theme-mininapse/issues/42#issuecomment-461545770
